### ISSUE TITLE
Did Cef Source Code have been changed and be re-compiled?

### ISSUE THREAD

**Issue by ArionTT** [daktronics/cef-mixer#12]
I try to changed the Cef version to v3.3359.1758 that was compiled by Cef.

I found the class CefRenderHandler contained in file cef_render_handler.h didn't have a member function define:
 `virtual void OnAcceleratedPaint(CefRefPtr<CefBrowser> browser,PaintElementType ,const RectList& dirtyRects,void* shared_handle,uint64 sync_key) {} `

So the IDE return me a error when I inherit from this class, but in your code it is all right.

**Comment by wesselsga** [comment]
`OnAcceleratePaint` is a new method I added in the pull request.  It doesn't exist in the official CEF repo, because the pull request has not been merged.
