### ISSUE TITLE
WPF .NET - texture is flipped and upside down 

### ISSUE THREAD

**Issue by EladBahar** [daktronics/cef-mixer#17]
Hi,
Im try to implement this solution with WPF off-screen application (with is basically d3d9ex).
i managed to render the shared texture (using CEFSHARP) and d3dImage.

the only issue that the frame is flipped and upside down  (see attached file).

maybe someone can direct me where in code is  the actual rendering to the shared texture ?
i though this is place i need to look for in order to flip the image ( or maybe the origin OGL texture)..

thanks,
b

![image](https://user-images.githubusercontent.com/6461532/51917789-f9b0a900-23e8-11e9-9a19-d92041429571.png)

**Comment by EladBahar** [comment]
thanks!,
i will try that, but im not sure i have access to the texture uv (d3dImage  is .net lib).

but thanks again to the tip...

**Comment by wesselsga** [comment]
You can probably use a ScaleTransform as discussed [here](https://stackoverflow.com/questions/3005219/how-to-flip-image-in-wpf)

`<ScaleTransform ScaleY="-1"/>`

**Comment by EladBahar** [comment]
WOW!
that did the trick!
thank u very much!!
