### ISSUE TITLE
OnAcceleratedPaint seems to be called before the buffer is rendered to

### ISSUE THREAD

**Issue by blattersturm** [daktronics/cef-mixer#4]
We currently have logic in our application that assumes the shared texture is copyable using CopySubresourceRegion at the time the browser signals an event (in this case, OnAcceleratedPaint).

However, even if we remove all dirty rectangle logic from our application and copy the full buffer (CopyResource) from the main game thread, it appears the last view change (e.g. keyboard input in a `<input>` element) hasn't rendered to the shared texture yet in all cases that OnAcceleratedPaint was called.

I don't see any immediate workaround either other than swapping the buffer _any time_ the keyed mutex is able to be acquired, and not just when signaled by CEF.

**Comment by wesselsga** [comment]
Hmm, you're absolutely right.  I'll be looking into it now.

**Comment by wesselsga** [comment]
This issue should be resolved.  I updated both the [cef pull request](https://bitbucket.org/chromiumembedded/cef/pull-requests/158) and the x64 sample binary distribution.

**Comment by wesselsga** [comment]
Isaac Richards (on bitbucket) has identified another updating issue with the fix.  Working on it now to update the pull request

**Comment by wesselsga** [comment]
Pull request + sample distribution was updated again with fixes
