### ISSUE TITLE
Video elements only shows first frame

### ISSUE THREAD

**Issue by mihe** [daktronics/cef-mixer#5]
Video files played with the `<video>` element only shows the first frame in `cefmixer`. Using the video link directly seems to work though.

Doesn't work: https://h.ma.pe/webmalpha/
Works: https://h.ma.pe/webmalpha/output.webm

Both seem to work fine in `cefclient` with `--off-screen-rendering-enabled`.

EDIT: I should note that it shows the same behavior regardless of video container/codec. Alpha or not is irrelevant as well.

**Comment by wesselsga** [comment]
I see the same issue in cefclient - built with the pull request integrated?  It is possible that the pull request I have broke the software rendering path ... I'm just not seeing how at the moment

**Comment by mihe** [comment]
I tested `cefclient` using the build provided by the [Spotify automated builds](http://opensource.spotify.com/cefbuilds/index.html).

**Comment by wesselsga** [comment]
Ok, I'll do some more digging on cef master without the pull request to see if it works there

**Comment by wesselsga** [comment]
Unless I'm crazy ... this doesnt work with cef master either.

**Comment by wesselsga** [comment]
I think we might be fighting a [new policy change in Chromium](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

Apparently, you will have to add the `muted` attribute to your video if you want the video element to start playing without user interaction.

I pulled the [https://h.ma.pe/webmalpha/](https://h.ma.pe/webmalpha/) and edited a local copy adding the muted attribute to your video element and it worked fine in cefmixer

**Comment by mihe** [comment]
You're absolutely right, good catch! I just confirmed that it happens in Chrome Canary 67.0.3367.0 as well. I figured the automated cefclient build would be more bleeding edge than Canary, but apparently not. :)

**Comment by Lange** [comment]
This policy can be disabled via a command-line flag:
```
--autoplay-policy=no-user-gesture-required
```

I tested this flag with a build of `cef-mixer`, and it worked as expected, allowing me to use the `.play()` method on `<video>` elements without user interaction.

**Comment by wesselsga** [comment]
Excellent.  Good tip - thanks for the info.
