### ISSUE TITLE
HTML texture stops updating after resize

### ISSUE THREAD

**Issue by wesselsga** [daktronics/cef-mixer#6]
Here is a [test build](https://s3.amazonaws.com/wesselsga/cef/freeze/cefmixer.7z) to try on machines that exhibit the issue of freezing after a resize.

If someone, could try this build on another machine exhibiting the issue - it would be greatly appreciated!

Thanks

**Comment by mihe** [comment]
Is this with or without the `SendExternalBeginFrame`? This build seems to work on the one machine we previously had issues on.

**Comment by wesselsga** [comment]
This build is with the new `SendExternalBeginFrame`

**Comment by wesselsga** [comment]
Thanks for testing this out, much appreciated!

**Comment by mihe** [comment]
No problem. It works fine on our other machine as well, for the record.

**Comment by wesselsga** [comment]
Should be able to leverage SendExternalBeginFrame to work around what I believe is a Chromium issue with `disable-gpu-vsync`
