### ISSUE TITLE
Conflicting documentation for shared_texture_sync_key

### ISSUE THREAD

**Issue by mihe** [daktronics/cef-mixer#7]
`html_layer.cpp` in cefmixer states `set the sync key to 0 so Chromium will setup the shared texture with a keyed mutex and sync on key 0` whereas the documentation in `cef_types_win.h` states `Set to 0 to NOT use a KeyedMutex associated with the shared textures`.

Judging by `OffscreenBrowserCompositorOutputSurface::IsValidSyncKey` I'm guessing the one in `cef_types_win.h` is incorrect?

**Comment by wesselsga** [comment]
My bad, yes the documentation is incorrect in `cef_types_win.h`.  I will update that.  0 is a valid key and Chromium will setup the shared texture when using key = 0.  Originally, I wanted to use 0 to mean disabled ... but it didn't work out.

**Comment by wesselsga** [comment]
The code comments should now be up to date in [PR158](https://bitbucket.org/chromiumembedded/cef/pull-requests/158/support-external-textures-in-osr-mode/diff)

Thanks!
