### ISSUE TITLE
CefSettings members have no effect

### ISSUE THREAD

**Issue by mihe** [daktronics/cef-mixer#9]
As far as I can tell the members added to `CefSettings` (`shared_texture_enabled`, `shared_texture_sync_key`, `external_begin_frame_enabled`) don't actually do anything. `CefSettingsTraits::set` in `cef_types_wrappers.h` don't seem accommodate for these members, so they all get discarded either way.

Any reason for them being there?

**Comment by wesselsga** [comment]
Ha! I must have been copy-paste happy there :smile:.  No, they don't belong on `CefSettings` just `CefWindowInfo`  Good catch.

**Comment by wesselsga** [comment]
[PR 158](https://bitbucket.org/chromiumembedded/cef/pull-requests/158/support-external-textures-in-osr-mode/commits) should have these members removed.
